AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/features/*'
    - 'test/test_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスとモジュールのドキュメンテーションは不要
Style/Documentation:
  Enabled: false

# ダブルクオーテーションを許可しない
Style/StringLiterals:
  Enabled: true

LineLength:
  Max: 120

# テストにはFrozen string literalは必要ない
FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'test/**/*'
