version: '2'
services:
  app:
    image: kentrino/neo-atnd
    volumes:
      - html:/var/www/html
      - run:/var/run
    environment:
      # required variables to run container
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DB_HOST: "${DB_HOST}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

      # required variables to run application correctly
      TWITTER_KEY: "${TWITTER_KEY}"
      TWITTER_SECRET: "${TWITTER_SECRET}"

      RAILS_ENV: production
  nginx:
    image: kentrino/nginx
    volumes_from:
      - app
    ports:
      - "80:80"
volumes:
  html:
    driver: local
  run:
    driver: local
