# TODO: FIX all
FROM kentrino/neo-atnd

ARG GROUP_ID
ARG USER_ID

ENV RAILS_ROOT=/var/www/app

RUN addgroup nginx -g "$GROUP_ID" && \
    adduser -D -H -G nginx -u $USER_ID nginx && \
    chown -R nginx:nginx $RAILS_ROOT && \
    chmod -R go-rwx $RAILS_ROOT && \

    # log files
    # socket file will get 777 by unicorn
    # TODO: should be changed to 770?
    chown nginx:nginx $RAILS_ROOT/log/nginx $RAILS_ROOT/tmp && \
    chmod g+rwx $RAILS_ROOT/log/nginx $RAILS_ROOT/tmp && \

    # public folder
    chown -R nginx:nginx $RAILS_ROOT/public && \
    chmod -R g+r $RAILS_ROOT/public

ADD . /var/www/app

USER app

ENTRYPOINT ["bundle", "exec"]
CMD ["unicorn", "-c", "./config/unicorn.rb"]
