version: '2'
services:
  app:
    image: kentrino/neo-atnd
    volumes:
      - html:/var/www/html
      - run:/var/run
    environment:
      APP_NAME: neo-atnd
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DB_HOST: "${DB_HOST}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
  nginx:
    image: kentrino/nginx
    volumes_from:
      - app
    ports:
      - "5000:80"
volumes:
  html:
    driver: local
  run:
    driver: local
