# TODO: FIX all
FROM nginx:1.9.15-alpine

# TODO: optimize nginx.conf for development
COPY docker-dev.nginx.conf /etc/nginx/nginx.conf
COPY docker-dev.vh.conf /etc/nginx/vh.conf

VOLUME /volume

ARG GROUP_ID
ARG USER_ID

RUN deluser nginx && \
    addgroup -S nginx -g $GROUP_ID && \
    adduser -S -D -H -G nginx -u $USER_ID nginx

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
